config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :order_details
  resources :order_members
  resources :orders
  resources :orders do
  resources :order_details
  end
  resources :group_members
  resources :groups
  resources :friends
  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'finshorder/:id' , :to => 'orders#finsh',:as => 'finsh'

  root 'users#index'
  resources :group_members do resources :users end

  post 'member/email/', to: 'order_members#add_member', as: 'email'
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  # belongs_to :user

 belongs_to :user, class_name: "User", foreign_key: "user_id"
 belongs_to :user, class_name: "User", foreign_key: "friend_id"

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    #@friends = Friend.all
    @friends=Friend.where(user_id: current_user.id)
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new
    @friend.user_id = params[:user_id]
    @friend.friend_id = params[:friend][:friend_id]
    # @friend1 = Friend.find_by_friend_id params[:friend][:friend_id]
    #@friend2 = Friend.find_by_user_id params[:user_id]
    @friend1=Friend.where(user_id: params[:user_id]).where(friend_id: params[:friend][:friend_id])
  if @friend1.nil
#if @friend1.nil? && @friend2.nil?
    respond_to do |format|
      if @friend.save
        #format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.html { redirect_to :action => 'index', notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  
  else
   respond_to do |format|
     format.html { redirect_to :action => 'index', notice: 'Friend was added before.' }
     format.json { render :show, status: :unprocessable_entity, location: @friend }

    end  
  end
end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:friend_id, :user_id)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Friends</h1>

<table>
  <thead>
    <tr>
      <th>Friend name</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
      <th>email</th>
    </tr>
  </thead>
<%= @friend1 %>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
       <!--  <td><%= friend.friend_id %></td> -->
        <td><%= friend.user.name if friend.user %></td>
        <td colspan="6"></td>
        <td><%= friend.user.email if friend.user %></td>
        <td colspan="3"></td>
        <td colspan="3"></td>
        <td><%= link_to 'unfriend', friend, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-default"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path ,class:"btn btn-primary"%>

app/views/friends/new.html.erb
<h1>New Friend</h1>
<style>
.add{
  min-height:250px;
  margin:10px;
  background-color:#eee;
  border-radius:10px;
}
h3{
  border-bottom:1px solid #ccc ;
}
</style>
<div class="add col-md-8 table-bordered" >
<h3>Add New Friend</h3>

<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div class="alert alert-success" id="notice">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= hidden_field_tag :user_id, current_user.id %>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.collection_select(:friend_id,User.where.not(id: current_user.id),:id,:name, { :prompt => "Select friend"},class: "form-control")  %>
  </div>
  <div class="actions">
    <%= f.submit "Add", class:"btn btn-default btn-primary"  %>
  </div>
 </div>
<% end %>


<%= link_to 'Back', orders_path %>
</div>

<%= link_to 'back to friends', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>name</strong>
  <%= @friend.user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @friend.user.email %>
</p>
<%= link_to 'Back', friends_path %>