config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :order_details
  resources :order_members
  resources :orders
  resources :orders do
  resources :order_details
  end
  resources :group_members
  resources :groups
  resources :friends
  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'finshorder/:id' , :to => 'orders#finsh',:as => 'finsh'

  root 'users#index'
  resources :group_members do resources :users end

  post 'member/email/', to: 'order_members#add_member', as: 'email'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :group_members
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    if(current_user)
      @groups = Group.all
    else
      redirect_to "/users/sign_in"
    end
    
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    # @members = GroupMember.find(@user.id, :include => :comments)
    @members = GroupMember.where( 'group_id = '+params[:id]).pluck(:user_id)
    @friends_of_user = []
    for userFriend in current_user.friend1 do
      @friends_of_user << User.where('id IN (?)',userFriend.friend_id).pluck(:id)
    end
    if(@members.count > 0)
      @friend_users = User.where('id IN (?)',@friends_of_user.map(&:first)).where('id NOT IN (?)',@members)
    else
      @friend_users = User.where('id IN (?)',@friends_of_user.map(&:first))
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
    # @users = User.where("id !=?",current_user.id)
  end

  # GET /groups/1/edit
  def edit

  end

  # POST /groups
  # POST /groups.json
  def create
    if(current_user)
      if(group_params[:name])
        @group = Group.new(group_params)
        @group.user_id= current_user.id
        
        respond_to do |format|
          if @group.save
            @notify = Notification.new
            @notify.user_id= current_user.id
            @notify.content = 'has created group named  "'+@group.name+'"'
            @notify.url = "/groups/"+@group.id.to_s
            @notify.save
            format.html { redirect_to '/groups/' , notice: 'Group was successfully created, add new members now.' }
            # format.json { render :show, status: :created, location: @group }
          else
            format.html { render :new }
            format.json { render json: @group.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:notice] = 'Group name is requierd.'
        redirect_to '/groups/new'

      end

    else
      redirect_to "/users/sign_in"
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        @notify = Notification.new
        @notify.user_id= current_user.id
        @notify.content = 'has updated group named  "'+@group.name+'"'
        @notify.url = "/groups/"+@group.id.to_s
        @notify.save
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.group_members.destroy
    
    @notify = Notification.new
        @notify.user_id= current_user.id
        @notify.content = 'has deleted group named  "'+@group.name+'"'
        @notify.url = "/groups/"
        @notify.save
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<style>

.divcontainer{
  height:330px;
  margin:10px;
  width:30%;
  background-color:#eee;
  border-radius:10px;
  overflow: scroll;
  padding: 10px;
  padding-top:5px;

}
h4  > a {
  border-bottom:1px solid #ccc ;
}
  .head:hover
  {
    background-color:#eee;
    color:black;
    text-decoration:none;
  }
.order{
  background-color:#2b0d33;
  border-radius:2px;
   border-bottom:1px solid #ccc ;
   overflow:hidden;
   padding:5px;
   padding-left: 10px;
   margin:2px;
   margin-top:8px;
   box-shadow:3px 3px 10px #333;
   color:white;

}
  .order:hover
  {
    background-color:white;
    color:#2b0d33;
  }
  .buttons > a , .link > i
  {
    margin-left:5px;
    font-size:16px;
    margin-top:10px;
    color:#333;
  }
   .link > i
  {

    margin-top:0px;
  }
  .buttons > a:hover, .link > i:hover
  {
    background-color:#eee;
    color:black;
  }
  .red
  {
    color:red;
  }
  .blue
  {
    color:blue;
  }
  .green
  {
    color:green;
  }
</style>
<p id="notice"><%= notice %></p>
<%= link_to 'New Group', new_group_path,  class:"pull-right btn btn-sm btn-default"%>
<h1>My Groups</h1>



    <% @groups.each do |group| %>
      <div class="divcontainer col-md-3">
        <div class="buttons col-md-4 pull-right" >
            
            <%= link_to group,class:"pull-right green", method: :delete, data: { confirm: 'Are you sure you want to delete this group !!?' } do %><i class="fa fa-close"></i><% end %>
            <%= link_to edit_group_path(group),class:"pull-right" do %><i class="fa fa-pencil-square-o"></i><% end %>
            
          <!--   <%= link_to new_group_member_path,class:"pull-right"  do %><i class="fa fa-user-plus"></i> <% end %> -->
          <!-- Large modal -->
          
            
            
          </div>
        <h4 class="col-md-7 pull-left">
          <%= link_to  '/groups/'+group.id.to_s ,class:"pull-left head" do %>
          <%=group.name%>
          <% end %>
        </h4>
          <% group.group_members.each  do |groupmember| %>
            <div class="order col-md-10 pull-left">
            <p><%= groupmember.user.name.inspect %>  
            <%= link_to 'X', groupmember, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-sm btn-danger pull-right"%></p>
            </div>
          <% end %>
      </div>
        
      </tr>
    <% end %>

app/views/groups/new.html.erb
<style>
.add{
  min-height:250px;
  margin:10px;
  background-color:#eee;
  border-radius:10px;
}
h3{
  border-bottom:1px solid #ccc ;
}
</style>
<div class="add col-md-8 table-bordered" >
<h3>Add New Group</h3>
<p id="notice"><%= notice %></p>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div class="alert alert-success" id="notice">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <div class=>
    <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Create Group" , class: "btn btn-default btn-primary" %> 

  </div>
 </div>
<% end %>


<%= link_to 'Back', orders_path %>
</div>

app/views/groups/show.html.erb
<style>

.divcontainer{
  height:330px;
  margin:10px;
  width:80%;
  background-color:#eee;
  border-radius:10px;
  overflow: scroll;
  padding: 10px;
  padding-top:5px;

}
h3{
  border-bottom:1px solid #ccc ;
}
.order{
  background-color:#fff;
  border-radius:2px;
  width:90%;
   border-bottom:1px solid #ccc ;
   overflow:hidden;
   padding:5px;
   padding-left: 10px;
   margin:2px;
   margin-top:8px;
   box-shadow:3px 3px 10px #333;

}
  .order:hover
  {
    background-color:#ccc;
  }
  .buttons > a , .link > i
  {
    margin-left:5px;
    font-size:16px;
    margin-top:20px;
    color:#333;
  }
   .link > i
  {

    margin-top:0px;
  }
  .buttons > a:hover, .link > i:hover
  {
    background-color:#eee;
    color:black;
  }
  .red
  {
    color:red;
  }
  .blue
  {
    color:blue;
  }
  .green
  {
    color:green;
  }
.user
{
  border-top:1px solid #bbb;
  width:100%;
  overflow:hidden;
  margin:10px 0px;
}
.order-user{
  background-color:#fff;
  border-radius:2px;
  width:12%;
   overflow:hidden;
   padding:5px;
   padding-bottom:0px;
   margin:5px;
   box-shadow:3px 3px 10px #333;

}
</style>
<p id="notice"><%= notice %></p>
<%= link_to 'New Group', new_group_path,  class:"pull-right btn btn-sm btn-default"%>
<h1>My Groups</h1>
      <div class="divcontainer">
        <div class="buttons col-md-6 pull-right">
            
            <%= link_to @group,class:"pull-right green", method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-close"></i><% end %>
            <%= link_to edit_group_path(@group),class:"pull-right" do %><i class="fa fa-pencil-square-o"></i><% end %>       
            
        </div>

        <h3><%= @group.name %>
          
        </h3>

        <% @group.group_members.each  do |groupmember| %>
          <div class="order">
          <p><%= groupmember.user.name %>  
          <%= link_to 'X', groupmember, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-sm btn-danger pull-right"%></p>
          </div>
        <% end %>
        <div class="user">
          <h4> Friends Out Of Group: </h4>
        <% @friend_users.each  do |fr|%>
          <div class="order-user">
            <%= form_for([GroupMember.new]) do |f| %>
              <%= hidden_field_tag :group_id, @group.id %>
              <%= hidden_field_tag :user_id, fr.id %>
              <%= fr.name %>  
              <%= f.submit "+" , class: "btn btn-sm btn-primary" %>
            <% end %>

          </div>

        <% end %>
        </div>
      </div>
        
      </tr>