config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :order_details
  resources :order_members
  resources :orders
  resources :orders do
  resources :order_details
  end
  resources :group_members
  resources :groups
  resources :friends
  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'finshorder/:id' , :to => 'orders#finsh',:as => 'finsh'

  root 'users#index'
  resources :group_members do resources :users end

  post 'member/email/', to: 'order_members#add_member', as: 'email'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_members
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  # mount_uploader :avatar, AvatarUploader

  # GET /orders
  # GET /orders.json
  def index
    if(current_user)
       @orders = Order.where(user_id: current_user.id)
    else
      redirect_to "/users/sign_in"
    end

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  def finsh
    @order = Order.find(params[:id])
    @order.status=0
    @order.save
    flash[:notice] = 'Order has finished and closed.'
    redirect_to '/orders/'
    # respond_to do |format|
    #   if @order.update(order_params)
    #       format.html { redirect_to :back, notice: 'Order member was successfully created.' }
    #       format.json { head :no_content}
    #     else
    #       format.html { redirect_to :back, notice: 'error in email' }
    #       format.json { head :no_content}
    #   end
    # end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    if(current_user)
      @order = Order.new(order_params)
      # @order.avatar = params[:file] # Assign a file like this, or
      @order.user_id = current_user.id
      @order.status=1
      respond_to do |format|
        if @order.save
          format.html { redirect_to @order, notice: 'Order was successfully created.' }
          format.json { render :show, status: :created, location: @order }
        else
          format.html { render :new }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/users/sign_in"
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
      @users = OrderMember.where(order_id: params[:id])
      @order_member = OrderMember.new
      @order_group = Group.new
      @notification = Notification.new
      # @users = Order_member.find_by order_id: params[:id]
      # @users = Order_member.all :conditions => (order_id ? ["order_id != ?", params[:id]] : [])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :resturant, :status, :user_id, :image)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :resturant %><br>
    <%= f.text_field :resturant %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class=" table table-striped" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Resturant</th>
      <th>invited</th>
      <th>join</th>
      <th>Status</th>

      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.resturant %></td>
        <% @count=OrderMember.where(order_id: order.id).count %>
        <td><%= @count %></td>
        <% @join=OrderMember.where(order_id: order.id,status_user: true).count %>
        <td><%= @join %></td>
        
        <% if order.status? %>
        <td>Waiting</td>
        <% else %>
        <td>Finish</td>
        <% end %>
        <td><%= link_to 'Show', '/orders/'+order.id.to_s+'/order_details',class: 'btn btn-primary'  %></td>
        <% if order.status? %>
        <td><%= link_to 'Finish',
           finsh_path(order),
           class: 'btn btn-info' %>
        </td>
        <td><%= link_to 'Add Friend', '/orders/'+order.id.to_s,class: 'btn btn-primary'  %></td>
         <% else %>
         <td><span>finshed</span></td>
         <td><span>canot add friend</span></td>
         <% end %>
        <td><%= link_to 'cancel', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<script type="text/javascript">
  
<%= link_to 'New Order', new_order_path , class: 'btn btn-success' %>

</script>

app/views/orders/new.html.erb
<style>
.add{
  min-height:250px;
  margin:10px;
  background-color:#eee;
  border-radius:10px;
}
h3{
  border-bottom:1px solid #ccc ;
}
</style>
<div class="add col-md-8 table-bordered" >
<h3>Start New Order</h3> 

<%= form_for(@order) do |f| %>

  <% if @order.errors.any? %>
    <div class="alert alert-success" id="notice">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=" form control field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :resturant %><br>
    <%= f.text_field :resturant %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<style>
.add{
  min-height:250px;
  margin:10px;
  background-color:#eee;
  border-radius:10px;
}
h3{
  border-bottom:1px solid #ccc ;
}
</style>

<div class="add col-md-5 table-bordered" >
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @order.name %>
  </p>

  <p>
    <strong>Resturant:</strong>
    <%= @order.resturant %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @order.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @order.user.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= @order.image %>
  </p>

    <div class="field">
    <!-- <form action="<%= email_path %>" method="POST" accept-charset="utf-8"> -->
    
      <%= form_for(@order_member) do |f| %>
      <%= f.label :'Add Email friend ' %><br>
      <%= f.text_field_tag 'email' %>
      <%= f.hidden_field_tag 'order_member[order_id]' ,"#{@order.id}"%>
      <%= f.hidden_field_tag 'order_member[status]' ,"0"%>
      <%= f.submit "Add" , class:"btn btn-primary" %>
    <br/>
      <%= form_for(@order_group) do |f| %>
      <%= f.label :'Add Groub Name' %><br>
      <%= f.text_field_tag 'group' %>
      <%= f.hidden_field_tag 'order_member[order_id]' ,"#{@order.id}"%>
      <%= f.hidden_field_tag 'order_member[status]' ,"0"%>
      <%= f.submit "Add" , class:"btn btn-primary" %>
      <% end %>
    <% end %>
    <!-- <input type="hidden" name="_method" value="patch" class="">
      <label> And Email friend & Groub Name</label>
      <br />
      <input type="hidden" id="path" name="order_id" value="<%= @order.id%>"></input>
      <input type="text"  id="member" name="email" class="member" ></input>
       <input type="submit" class="btn btn-primary"></input>
     -->
      <!-- <button type="button" id="add_member" class="btn btn-primary">Add</button> -->
    <!-- </form> -->
  </div>
  <%= link_to 'Edit', edit_order_path(@order) %> |
  <%= link_to 'Back', orders_path %>
</div>

<div class="add col-md-5 table-bordered" >

  <% if @users %>
    <% @users.each do |user| %>
    <div class="order row">
      <h5 class="col-md-3">
        <i class="fa fa-paperclip" aria-hidden="true"></i>  <%= user.user.name %>
      </h5>
      <h6 class="col-md-7" style="color: red">
      <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
      </h6>
       
    </div>
    <% end %>
    <% else %>
    <h1>empty</h1>
  <% end %>

</div>
<!-- 
<script type="text/javascript">
  
        // console.log('sfdf');
$(function () {
 $('body').on('click', '#add_member', function ()
  {
      var member=$('#member').val();
      var path=$('#path').val();
      console.log(path);
      // row_id = $(this).data('rowid');
       var user = {}
       user.email=member
      console.log(user);

        $.ajax
                ({
                    // url: 'users/email/:abanob.todary@gmail.com',
                    // url:'http://localhost:3000/users/1',
                    url:path,
                    type: 'POST',
                    data: user,
                    success: function (data)
                    {
                        console.log(data);
                    }

                });

  });

});
</script> -->